"""empty message

Revision ID: b030a1e5cfae
Revises: d6198d1addf3
Create Date: 2022-08-09 14:54:57.866730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b030a1e5cfae'
down_revision = 'd6198d1addf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('folder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'folder_name')
    # ### end Alembic commands ###
