"""empty message

Revision ID: d6198d1addf3
Revises: 4a63bfb3154d
Create Date: 2022-08-09 12:06:32.678901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6198d1addf3'
down_revision = '4a63bfb3154d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image', sa.String(), nullable=False))
    op.drop_column('books', 'value')
    op.drop_column('users', 'coins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('books', 'image')
    # ### end Alembic commands ###
